#!/usr/bin/env bash -e

if [ -e .env ]
then
  echo "-----> Existing .env file found, 'rm .env' to overwrite it next time."
else
  echo "-----> Installing .env file. WARNING: This will fail if you're not a Test Double Agent!"
  git clone git@github.com:testdouble/mi5.git loldeleteme
  mv loldeleteme/env-files/present.development.env .env
  rm -rf loldeleteme
  echo "-----> Development .env installed."
fi

echo "-----> Sourcing .env"
source .env

echo "-----> Installing dependencies"
bundle

echo "-----> Setting up database"
bundle exec rake db:setup

echo "-----> Setup complete. Run 'rails s' to start a server"
